site_name: MDS - Squad 8 - Certifik8
site_url: https://squad8.com/
repo_url: https://github.com/fga-eps-mds/2022-2-Certifik8.git
repo_name: 2022-2-Certifik8


nav:
    - Página Principal: docs/index.md

markdown_extensions:
  - attr_list
  - md_in_html
  
theme:
    icon:
        repo: fontawesome/brands/github
    name: material
    navigation_depth: 4
    extra_css:
        - stylesheets/extra.css
    palette:
        accent: green
        scheme: slate
        primary: purple
    
    logo: assets/icons/Certifik8.ico

