site_name: Squad 8 - MDS
site_url: https://squad8.com/
nav:
    - Home: README.md
    - Objetivos: pages/objetivo.md
    - Projeto:
        - TAP: pages/TAP.md
        - Documento de Visão: pages/Documento_de_Visao.md
        - Post Mortem: pages/Post_Mortem.md
        - Arquitetura: pages/DocumentoDeArquitetura.md
    - Equipe:
        - Atas: pages/atas_Sprint_Review_E_Retro.md
        - Backlog: pages/backlog.md

theme:
    name: material  
    nav_style: dark
    navigation_depth: 4